using System.Reflection;
using STS2RitsuLib.Patching.Builders;
using STS2RitsuLib.Patching.Models;
using STS2RitsuLib.Patching.Rules;

namespace STS2RitsuLib.Patching.Core
{
    /// <summary>
    ///     Extension methods for ModPatcher to support advanced patch builders.
    /// </summary>
    public static class ModPatcherExtensions
    {
        /// <summary>
        ///     Register patches generated from a rule.
        /// </summary>
        public static void RegisterFromRule(this ModPatcher patcher, ModPatchRule rule,
            params ReadOnlySpan<Assembly> assemblies)
        {
            var patches = rule.GeneratePatches(assemblies);
            patcher.RegisterPatches(patches);
        }

        /// <summary>
        ///     Register patches from an IModPatchProvider type.
        /// </summary>
        public static void RegisterPatches<T>(this ModPatcher patcher) where T : IModPatches
        {
            T.AddTo(patcher);
        }

        /// <summary>
        ///     Register patches from an IPatchMethod type (single patch)
        ///     or a class containing multiple IPatchMethod nested classes.
        /// </summary>
        public static void RegisterPatch<TPatch>(this ModPatcher patcher) where TPatch : IPatchMethod
        {
            var patchInfos = IPatchMethod.CreatePatchInfos<TPatch>();
            patcher.RegisterPatches(patchInfos);
        }

        /// <summary>
        ///     Apply runtime-discovered patches generated by a dynamic builder.
        /// </summary>
        public static bool ApplyDynamic(this ModPatcher patcher, DynamicPatchBuilder builder,
            bool rollbackOnCriticalFailure = false)
        {
            ArgumentNullException.ThrowIfNull(builder);
            return patcher.ApplyDynamicPatches(builder.Patches, rollbackOnCriticalFailure);
        }
    }
}
